export const data = {
    products: [
        {
            id: 1,
            title: 'Product 1',
            description: 'Product 1 description',
            price: 100,
            image: '/23.svg',
        },
        {
            id: 2,
            title: 'Product 2',
            description: 'Product 2 description',
            price: 200,
            image: '/46.svg',
        },
        {
            id: 3,
            title: 'Product 3',
            description: 'Product 3 description',
            price: 300,
            image: '/72.svg',
        },
        {
            id: 4,
            title: 'Product 4',
            description: 'Product 4 description',
            price: 400,
            image: '/73.svg',
        },
        {
            id: 5,
            title: 'Product 5',
            description: 'Product 5 description',
            price: 500,
            image: '/74.svg',
        },
        {
            id: 6,
            title: 'Product 6',
            description: 'Product 6 description',
            price: 600,
            image: '/75.svg',
        },
        {
            id: 7,
            title: 'Product 7',
            description: 'Product 7 description',
            price: 700,
            image: '/76.svg',
        },
        {
            id: 8,
            title: 'Product 8',
            description: 'Product 8 description',
            price: 800,
            image: '/77.svg',
        },
        {
            id: 9,
            title: 'Product 9',
            description: 'Product 9 description',
            price: 900,
            image: '/78.svg',
        },
        {
            id: 10,
            title: 'Product 10',
            description: 'Product 10 description',
            price: 100,
            image: '/79.svg',
        }, {
            id: 12,
            title: 'Product 12',
            description: 'Product 12 description',
            price: 200,
            image: '/80.svg',
        },
        {
            id: 13,
            title: 'Product 13',
            description: 'Product 13 description',
            price: 300,
            image: '/81.svg',
        },
        {
            id: 14,
            title: 'Product 14',
            description: 'Product 14 description',
            price: 400,
            image: '/82.svg',
        },
        {
            id: 15,
            title: 'Product 15',
            description: 'Product 15 description',
            price: 500,
            image: '/83.svg',
        },
        {
            id: 16,
            title: 'Product 16',
            description: 'Product 16 description',
            price: 600,
            image: '/84.svg',
        },
        {
            id: 17,
            title: 'Product 17',
            description: 'Product 17 description',
            price: 700,
            image: '/85.svg',
        },
        {
            id: 18,
            title: 'Product 18',
            description: 'Product 18 description',
            price: 800,
            image: '/86.svg',
        },
        {
            id: 19,
            title: 'Product 19',
            description: 'Product 19 description',
            price: 900,
            image: '/87.svg',
        },
        {
            id: 20,
            title: 'Product 20',
            description: 'Product 20 description',
            price: 100,
            image: '/89.svg',
        },
        {
            id: 21,
            title: 'Product 21',
            description: 'Product 21 description',
            price: 200,
            image: '/90.svg',
        },
        {
            id: 22,
            title: 'Product 22',
            description: 'Product 22 description',
            price: 300,
            image: '/91.svg',
        },
        {
            id: 23,
            title: 'Product 23',
            description: 'Product 23 description',
            price: 400,
            image: '/92.svg',
        },
        {
            id: 24,
            title: 'Product 24',
            description: 'Product 24 description',
            price: 500,
            image: '/93.svg',
        },
        {
            id: 25,
            title: 'Product 25',
            description: 'Product 25 description',
            price: 500,
            image: '/94.svg',
        }
    ]
}